naming:
    PackageNaming:
        active: true
        packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9_]*)*'

complexity:
    LongMethod:
        active: true
        threshold: 60
        excludes: [ '**/test/**' ]

exceptions:
    TooGenericExceptionCaught:
        active: true
        excludes: [ '**/test/**' ]
        exceptionNames:
            - 'Exception'
            - 'ArrayIndexOutOfBoundsException'
            - 'Error'
            - 'IllegalMonitorStateException'
            - 'IndexOutOfBoundsException'
            - 'NullPointerException'
            - 'RuntimeException'
            - 'Throwable'

performance:
    SpreadOperator:
        active: true
        excludes: [ '**/test/**', '**/*Application.kt' ]
style:
    MaxLineLength:
        active: true
        maxLineLength: 300
        excludePackageStatements: true
        excludeImportStatements: true
        excludeCommentStatements: false
        excludes: [ '**/test/**' ]

    ReturnCount:
        active: true
        max: 10
        excludedFunctions: 'equals'
        excludeLabeled: false
        excludeReturnFromLambda: true
        excludeGuardClauses: false
    ThrowsCount:
        active: true
        max: 10
        excludeGuardClauses: false
    UnnecessaryAbstractClass:
        active: false
